import Foundation
import UIKit

enum PDFProposalService {
    static func render(proposal: Proposal, lead: Lead?, profile: BusinessProfile?) throws -> URL {
        let directory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Proposals", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let safeTitle = proposal.title
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: "-")
        let fileURL = directory.appendingPathComponent("\(safeTitle)-\(proposal.id.uuidString.prefix(8)).pdf")

        let pageRect = CGRect(x: 0, y: 0, width: 595.2, height: 841.8)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        try renderer.writePDF(to: fileURL) { context in
            let margin: CGFloat = 44
            let contentWidth = pageRect.width - (margin * 2)
            var y = margin

            func beginPageIfNeeded(for height: CGFloat) {
                if y + height > pageRect.height - margin {
                    context.beginPage()
                    y = margin
                }
            }

            func draw(_ text: String, font: UIFont, color: UIColor = .label, spacing: CGFloat = 10) {
                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color
                ]
                let rect = NSString(string: text).boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )
                beginPageIfNeeded(for: ceil(rect.height) + spacing)
                NSString(string: text).draw(
                    with: CGRect(x: margin, y: y, width: contentWidth, height: ceil(rect.height) + 2),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )
                y += ceil(rect.height) + spacing
            }

            context.beginPage()

            let brand = profile?.brandingName.isEmpty == false ? profile?.brandingName ?? AppConstants.appName : AppConstants.appName
            draw(brand, font: .systemFont(ofSize: 14, weight: .semibold), color: .systemTeal, spacing: 6)
            draw(proposal.title, font: .systemFont(ofSize: 28, weight: .bold), spacing: 12)

            if let lead {
                draw("Prepared for \(lead.name) | \(lead.serviceRequested) | \(proposal.estimatedValue.currencyFormatted)", font: .systemFont(ofSize: 12), color: .secondaryLabel, spacing: 18)
            } else {
                draw("Estimated value: \(proposal.estimatedValue.currencyFormatted)", font: .systemFont(ofSize: 12), color: .secondaryLabel, spacing: 18)
            }

            proposal.content
                .components(separatedBy: "\n")
                .forEach { paragraph in
                    let trimmed = paragraph.trimmingCharacters(in: .whitespaces)
                    draw(trimmed.isEmpty ? " " : trimmed, font: .systemFont(ofSize: 12), spacing: trimmed.isEmpty ? 4 : 8)
                }

            draw(profile?.proposalFooter ?? "Review all AI-assisted wording, estimates, and terms before sending.", font: .italicSystemFont(ofSize: 10), color: .secondaryLabel, spacing: 4)
            draw("Generated by \(AppConstants.appName). AI suggestions should be reviewed. Pricing estimates are not guaranteed.", font: .italicSystemFont(ofSize: 9), color: .secondaryLabel, spacing: 0)
        }

        return fileURL
    }
}
