import Foundation

struct RemoteAIService: AIService {
    private let endpoint: URL
    private let urlSession: URLSession

    init(endpoint: URL = AppConstants.backendURL, urlSession: URLSession = .shared) {
        self.endpoint = endpoint
        self.urlSession = urlSession
    }

    func qualifyLead(_ lead: Lead, businessType: BusinessType, photos: [LeadPhoto]) async throws -> AILeadQualification {
        let response = try await post(module: "qualifyLead", lead: lead, businessType: businessType, notes: lead.notes, photos: photos)
        let score = response.leadScore ?? 60
        let estimate = MockAIServiceValueHelper.estimatedValueFallback(for: lead, businessType: businessType)
        return AILeadQualification(
            leadScore: score,
            projectValueEstimate: estimate,
            urgencyLevel: lead.urgency.displayName,
            conversionLikelihood: Double(score) / 100,
            recommendedAction: response.summary ?? "Review lead details and confirm the next step.",
            followUpTimingSuggestion: "Follow up within 24 hours unless urgency requires a faster response.",
            category: score >= 80 ? .hot : score >= 55 ? .warm : .cold
        )
    }

    func generateProposal(for lead: Lead, businessType: BusinessType, qualification: QualificationResult?) async throws -> AIProposalDraft {
        let response = try await post(module: "generateProposal", lead: lead, businessType: businessType, notes: lead.notes, photos: [])
        let estimate = qualification?.projectValueEstimate ?? MockAIServiceValueHelper.estimatedValueFallback(for: lead, businessType: businessType)
        let content = response.proposal ?? "Proposal content was not returned by the backend."
        return AIProposalDraft(
            title: "\(lead.serviceRequested) Proposal",
            content: content,
            estimatedValue: estimate,
            serviceBreakdown: [],
            pricingStructure: "Backend-generated proposal.",
            optionalUpsells: [],
            timelineEstimate: "Timeline to be confirmed.",
            exclusions: []
        )
    }

    func generateFollowUp(for lead: Lead, type: FollowUpType, tone: FollowUpTone, context: String) async throws -> AIFollowUpDraft {
        let response = try await post(module: "generateFollowUp", lead: lead, businessType: .localContractor, notes: context, photos: [])
        return AIFollowUpDraft(
            type: type,
            tone: tone,
            content: response.followUp ?? "Follow up with \(lead.name) about \(lead.serviceRequested)."
        )
    }

    func summarizeVoiceNotes(_ transcript: String, businessType: BusinessType) async throws -> VoiceLeadSummary {
        let placeholderLead = Lead(name: "Voice note", serviceRequested: businessType.displayName, notes: transcript)
        let response = try await post(module: "summarizeVoiceNotes", lead: placeholderLead, businessType: businessType, notes: transcript, photos: [])
        let summary = response.summary ?? transcript
        return VoiceLeadSummary(
            leadSummary: summary,
            quoteNotes: "Review backend summary and convert key details into quote notes.",
            followUpTasks: "Create a follow-up task after reviewing the transcript.",
            crmNotes: "Generated by secure backend placeholder."
        )
    }

    func generateSalesInsights(
        leads: [Lead],
        proposals: [Proposal],
        followUps: [FollowUpMessage],
        businessType: BusinessType
    ) async throws -> SalesInsights {
        try await MockAIService().generateSalesInsights(
            leads: leads,
            proposals: proposals,
            followUps: followUps,
            businessType: businessType
        )
    }

    private func post(
        module: String,
        lead: Lead,
        businessType: BusinessType,
        notes: String,
        photos: [LeadPhoto]
    ) async throws -> RemoteAIResponse {
        guard endpoint.absoluteString != "https://YOUR_BACKEND_URL.com/leadpilot-iq" else {
            throw AIServiceError.backendNotConfigured
        }

        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try JSONEncoder().encode(RemoteAIRequest(
            module: module,
            businessType: businessType.displayName,
            serviceRequested: lead.serviceRequested,
            budgetRange: lead.budgetRange,
            notes: notes,
            images: photos.compactMap { $0.imageData?.base64EncodedString() }
        ))

        let (data, response) = try await urlSession.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse, (200..<300).contains(httpResponse.statusCode) else {
            throw AIServiceError.invalidResponse
        }
        return try JSONDecoder().decode(RemoteAIResponse.self, from: data)
    }
}

private struct RemoteAIRequest: Codable {
    var module: String
    var businessType: String
    var serviceRequested: String
    var budgetRange: String
    var notes: String
    var images: [String]
}

private struct RemoteAIResponse: Codable {
    var leadScore: Int?
    var proposal: String?
    var followUp: String?
    var summary: String?
}

private enum MockAIServiceValueHelper {
    static func estimatedValueFallback(for lead: Lead, businessType: BusinessType) -> Double {
        if let number = lead.budgetRange
            .components(separatedBy: CharacterSet.decimalDigits.inverted)
            .compactMap({ Double($0) })
            .max() {
            return max(number, 100)
        }
        return businessType.defaultEstimate
    }
}
